basePath: /api/v1
definitions:
  exoplanets.Exoplanet:
    properties:
      hostName:
        type: string
      id:
        type: integer
      planetName:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    name: digitalsquid7
  description: This is a sample server celler server.
  title: Swagger Example API
  version: "1.0"
paths:
  /exoplanets:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/exoplanets.Exoplanet'
      summary: Read a list of exoplanetsapi
      tags:
      - exoplanetsapi
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
